
# project.mak defines the default 'all' target that reliess on TARGETNAMES
TARGETNAMES = \
	string \
	cin-iostream \
	cout-iostream \
	file-iostream \
	iterator \
	list \
	pair \
	# vector

-include ../project.mak
