
# project.mak defines the default 'all' target that reliess on TARGETNAMES
TARGETNAMES = \
	class \
	struct \
	const-safe \
	constructor \
	implicit-explicit \
	namespace \
	this \
	overload-op \
	overload-func \
	overload-conv \
	newdelete \
	exceptions \
	functor \

-include ../project.mak
